// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: raft.proto

package raft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex  int32                  `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm   int32                  `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

func (x *RequestVoteRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RequestVoteRequest) GetLastLogIndex() int32 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() int32 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{1}
}

func (x *RequestVoteResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

// payloads for append entries
type UserPayload struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	FirstName                string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName                 string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	HashedPassword           string                 `protobuf:"bytes,3,opt,name=hashedPassword,proto3" json:"hashedPassword,omitempty"`
	Email                    string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	DateOfBirth              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	IdentificationNumber     string                 `protobuf:"bytes,6,opt,name=identificationNumber,proto3" json:"identificationNumber,omitempty"`
	IdentificationImageFront string                 `protobuf:"bytes,7,opt,name=identificationImageFront,proto3" json:"identificationImageFront,omitempty"`
	IdentificationImageBack  string                 `protobuf:"bytes,8,opt,name=identificationImageBack,proto3" json:"identificationImageBack,omitempty"`
	PrevPW                   string                 `protobuf:"bytes,9,opt,name=prevPW,proto3" json:"prevPW,omitempty"`
	NewPW                    string                 `protobuf:"bytes,10,opt,name=newPW,proto3" json:"newPW,omitempty"`
	UserID                   int64                  `protobuf:"varint,11,opt,name=userID,proto3" json:"userID,omitempty"`
	Action                   string                 `protobuf:"bytes,12,opt,name=action,proto3" json:"action,omitempty"` // create, update, delete
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UserPayload) Reset() {
	*x = UserPayload{}
	mi := &file_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPayload) ProtoMessage() {}

func (x *UserPayload) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPayload.ProtoReflect.Descriptor instead.
func (*UserPayload) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{2}
}

func (x *UserPayload) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserPayload) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserPayload) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

func (x *UserPayload) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserPayload) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UserPayload) GetIdentificationNumber() string {
	if x != nil {
		return x.IdentificationNumber
	}
	return ""
}

func (x *UserPayload) GetIdentificationImageFront() string {
	if x != nil {
		return x.IdentificationImageFront
	}
	return ""
}

func (x *UserPayload) GetIdentificationImageBack() string {
	if x != nil {
		return x.IdentificationImageBack
	}
	return ""
}

func (x *UserPayload) GetPrevPW() string {
	if x != nil {
		return x.PrevPW
	}
	return ""
}

func (x *UserPayload) GetNewPW() string {
	if x != nil {
		return x.NewPW
	}
	return ""
}

func (x *UserPayload) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type AdminPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FirstName      string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName       string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	HashedPassword string                 `protobuf:"bytes,3,opt,name=hashedPassword,proto3" json:"hashedPassword,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AdminID        int64                  `protobuf:"varint,5,opt,name=adminID,proto3" json:"adminID,omitempty"`
	UserId         int64                  `protobuf:"varint,6,opt,name=userId,proto3" json:"userId,omitempty"`
	Action         string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminPayload) Reset() {
	*x = AdminPayload{}
	mi := &file_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPayload) ProtoMessage() {}

func (x *AdminPayload) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPayload.ProtoReflect.Descriptor instead.
func (*AdminPayload) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{3}
}

func (x *AdminPayload) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AdminPayload) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AdminPayload) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

func (x *AdminPayload) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminPayload) GetAdminID() int64 {
	if x != nil {
		return x.AdminID
	}
	return 0
}

func (x *AdminPayload) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type WalletOperationPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet1       int64                  `protobuf:"varint,1,opt,name=wallet1,proto3" json:"wallet1,omitempty"`
	Wallet2       int64                  `protobuf:"varint,2,opt,name=wallet2,proto3" json:"wallet2,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletOperationPayload) Reset() {
	*x = WalletOperationPayload{}
	mi := &file_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletOperationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletOperationPayload) ProtoMessage() {}

func (x *WalletOperationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletOperationPayload.ProtoReflect.Descriptor instead.
func (*WalletOperationPayload) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{4}
}

func (x *WalletOperationPayload) GetWallet1() int64 {
	if x != nil {
		return x.Wallet1
	}
	return 0
}

func (x *WalletOperationPayload) GetWallet2() int64 {
	if x != nil {
		return x.Wallet2
	}
	return 0
}

func (x *WalletOperationPayload) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WalletOperationPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogIndex  int32                  `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm   int32                  `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  int32                  `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{5}
}

func (x *AppendEntriesRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesRequest) GetPrevLogIndex() int32 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() int32 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() int32 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type LogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Term           int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	ReferenceTable string                 `protobuf:"bytes,2,opt,name=referenceTable,proto3" json:"referenceTable,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LogEntry_UserPayload
	//	*LogEntry_AdminPayload
	//	*LogEntry_WalletOperationPayload
	Payload       isLogEntry_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{6}
}

func (x *LogEntry) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetReferenceTable() string {
	if x != nil {
		return x.ReferenceTable
	}
	return ""
}

func (x *LogEntry) GetPayload() isLogEntry_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LogEntry) GetUserPayload() *UserPayload {
	if x != nil {
		if x, ok := x.Payload.(*LogEntry_UserPayload); ok {
			return x.UserPayload
		}
	}
	return nil
}

func (x *LogEntry) GetAdminPayload() *AdminPayload {
	if x != nil {
		if x, ok := x.Payload.(*LogEntry_AdminPayload); ok {
			return x.AdminPayload
		}
	}
	return nil
}

func (x *LogEntry) GetWalletOperationPayload() *WalletOperationPayload {
	if x != nil {
		if x, ok := x.Payload.(*LogEntry_WalletOperationPayload); ok {
			return x.WalletOperationPayload
		}
	}
	return nil
}

type isLogEntry_Payload interface {
	isLogEntry_Payload()
}

type LogEntry_UserPayload struct {
	UserPayload *UserPayload `protobuf:"bytes,3,opt,name=userPayload,proto3,oneof"`
}

type LogEntry_AdminPayload struct {
	AdminPayload *AdminPayload `protobuf:"bytes,4,opt,name=adminPayload,proto3,oneof"`
}

type LogEntry_WalletOperationPayload struct {
	WalletOperationPayload *WalletOperationPayload `protobuf:"bytes,5,opt,name=walletOperationPayload,proto3,oneof"`
}

func (*LogEntry_UserPayload) isLogEntry_Payload() {}

func (*LogEntry_AdminPayload) isLogEntry_Payload() {}

func (*LogEntry_WalletOperationPayload) isLogEntry_Payload() {}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{7}
}

func (x *AppendEntriesResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_raft_proto protoreflect.FileDescriptor

const file_raft_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"raft.proto\x12\x04raft\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n" +
	"\x12RequestVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12 \n" +
	"\vcandidateId\x18\x02 \x01(\tR\vcandidateId\x12\"\n" +
	"\flastLogIndex\x18\x03 \x01(\x05R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x04 \x01(\x05R\vlastLogTerm\"K\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12 \n" +
	"\vvoteGranted\x18\x02 \x01(\bR\vvoteGranted\"\xcb\x03\n" +
	"\vUserPayload\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12&\n" +
	"\x0ehashedPassword\x18\x03 \x01(\tR\x0ehashedPassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12<\n" +
	"\vdateOfBirth\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x122\n" +
	"\x14identificationNumber\x18\x06 \x01(\tR\x14identificationNumber\x12:\n" +
	"\x18identificationImageFront\x18\a \x01(\tR\x18identificationImageFront\x128\n" +
	"\x17identificationImageBack\x18\b \x01(\tR\x17identificationImageBack\x12\x16\n" +
	"\x06prevPW\x18\t \x01(\tR\x06prevPW\x12\x14\n" +
	"\x05newPW\x18\n" +
	" \x01(\tR\x05newPW\x12\x16\n" +
	"\x06userID\x18\v \x01(\x03R\x06userID\x12\x16\n" +
	"\x06action\x18\f \x01(\tR\x06action\"\xd0\x01\n" +
	"\fAdminPayload\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12&\n" +
	"\x0ehashedPassword\x18\x03 \x01(\tR\x0ehashedPassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\aadminID\x18\x05 \x01(\x03R\aadminID\x12\x16\n" +
	"\x06userId\x18\x06 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\"|\n" +
	"\x16WalletOperationPayload\x12\x18\n" +
	"\awallet1\x18\x01 \x01(\x03R\awallet1\x12\x18\n" +
	"\awallet2\x18\x02 \x01(\x03R\awallet2\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"\xda\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x1a\n" +
	"\bleaderId\x18\x02 \x01(\tR\bleaderId\x12\"\n" +
	"\fprevLogIndex\x18\x03 \x01(\x05R\fprevLogIndex\x12 \n" +
	"\vprevLogTerm\x18\x04 \x01(\x05R\vprevLogTerm\x12(\n" +
	"\aentries\x18\x05 \x03(\v2\x0e.raft.LogEntryR\aentries\x12\"\n" +
	"\fleaderCommit\x18\x06 \x01(\x05R\fleaderCommit\"\x9a\x02\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12&\n" +
	"\x0ereferenceTable\x18\x02 \x01(\tR\x0ereferenceTable\x125\n" +
	"\vuserPayload\x18\x03 \x01(\v2\x11.raft.UserPayloadH\x00R\vuserPayload\x128\n" +
	"\fadminPayload\x18\x04 \x01(\v2\x12.raft.AdminPayloadH\x00R\fadminPayload\x12V\n" +
	"\x16walletOperationPayload\x18\x05 \x01(\v2\x1c.raft.WalletOperationPayloadH\x00R\x16walletOperationPayloadB\t\n" +
	"\apayload\"E\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\x94\x01\n" +
	"\x04Raft\x12B\n" +
	"\vRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\x12H\n" +
	"\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponseB%Z#github.com/IndraS1998/DBL/raft/raftb\x06proto3"

var (
	file_raft_proto_rawDescOnce sync.Once
	file_raft_proto_rawDescData []byte
)

func file_raft_proto_rawDescGZIP() []byte {
	file_raft_proto_rawDescOnce.Do(func() {
		file_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)))
	})
	return file_raft_proto_rawDescData
}

var file_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_raft_proto_goTypes = []any{
	(*RequestVoteRequest)(nil),     // 0: raft.RequestVoteRequest
	(*RequestVoteResponse)(nil),    // 1: raft.RequestVoteResponse
	(*UserPayload)(nil),            // 2: raft.UserPayload
	(*AdminPayload)(nil),           // 3: raft.AdminPayload
	(*WalletOperationPayload)(nil), // 4: raft.WalletOperationPayload
	(*AppendEntriesRequest)(nil),   // 5: raft.AppendEntriesRequest
	(*LogEntry)(nil),               // 6: raft.LogEntry
	(*AppendEntriesResponse)(nil),  // 7: raft.AppendEntriesResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_raft_proto_depIdxs = []int32{
	8, // 0: raft.UserPayload.dateOfBirth:type_name -> google.protobuf.Timestamp
	6, // 1: raft.AppendEntriesRequest.entries:type_name -> raft.LogEntry
	2, // 2: raft.LogEntry.userPayload:type_name -> raft.UserPayload
	3, // 3: raft.LogEntry.adminPayload:type_name -> raft.AdminPayload
	4, // 4: raft.LogEntry.walletOperationPayload:type_name -> raft.WalletOperationPayload
	0, // 5: raft.Raft.RequestVote:input_type -> raft.RequestVoteRequest
	5, // 6: raft.Raft.AppendEntries:input_type -> raft.AppendEntriesRequest
	1, // 7: raft.Raft.RequestVote:output_type -> raft.RequestVoteResponse
	7, // 8: raft.Raft.AppendEntries:output_type -> raft.AppendEntriesResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_raft_proto_init() }
func file_raft_proto_init() {
	if File_raft_proto != nil {
		return
	}
	file_raft_proto_msgTypes[6].OneofWrappers = []any{
		(*LogEntry_UserPayload)(nil),
		(*LogEntry_AdminPayload)(nil),
		(*LogEntry_WalletOperationPayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_proto_goTypes,
		DependencyIndexes: file_raft_proto_depIdxs,
		MessageInfos:      file_raft_proto_msgTypes,
	}.Build()
	File_raft_proto = out.File
	file_raft_proto_goTypes = nil
	file_raft_proto_depIdxs = nil
}
